// <auto-generated />
using System;
using EFApiSwaggerOdev.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFApiSwaggerOdev.Migrations
{
    [DbContext(typeof(MarketlerSwaggerApiDbContext))]
    partial class MarketlerSwaggerApiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EFApiSwaggerOdev.Models.Calisan", b =>
                {
                    b.Property<int>("CalisanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CalisanID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CalisanId"), 1L, 1);

                    b.Property<string>("CalisanAd")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CalisanGorev")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("CalisanYas")
                        .HasColumnType("int");

                    b.Property<int?>("MarketId")
                        .HasColumnType("int")
                        .HasColumnName("MarketID");

                    b.HasKey("CalisanId");

                    b.HasIndex("MarketId");

                    b.ToTable("Calisan", (string)null);
                });

            modelBuilder.Entity("EFApiSwaggerOdev.Models.Market", b =>
                {
                    b.Property<int>("MarketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MarketID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MarketId"), 1L, 1);

                    b.Property<string>("MarketAd")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MarketAdres")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MarketKod")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("SubeId")
                        .HasColumnType("int")
                        .HasColumnName("SubeID");

                    b.HasKey("MarketId");

                    b.HasIndex("SubeId");

                    b.ToTable("Market", (string)null);
                });

            modelBuilder.Entity("EFApiSwaggerOdev.Models.Sube", b =>
                {
                    b.Property<int>("SubeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SubeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubeId"), 1L, 1);

                    b.Property<string>("SubeAd")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("SubeCalisan")
                        .HasColumnType("int");

                    b.Property<string>("SubeKonum")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("SubeId");

                    b.ToTable("Sube", (string)null);
                });

            modelBuilder.Entity("EFApiSwaggerOdev.Models.Calisan", b =>
                {
                    b.HasOne("EFApiSwaggerOdev.Models.Market", "Market")
                        .WithMany("Calisans")
                        .HasForeignKey("MarketId")
                        .HasConstraintName("FK_Calisan_Market");

                    b.Navigation("Market");
                });

            modelBuilder.Entity("EFApiSwaggerOdev.Models.Market", b =>
                {
                    b.HasOne("EFApiSwaggerOdev.Models.Sube", "Sube")
                        .WithMany("Markets")
                        .HasForeignKey("SubeId")
                        .HasConstraintName("FK_Market_Sube");

                    b.Navigation("Sube");
                });

            modelBuilder.Entity("EFApiSwaggerOdev.Models.Market", b =>
                {
                    b.Navigation("Calisans");
                });

            modelBuilder.Entity("EFApiSwaggerOdev.Models.Sube", b =>
                {
                    b.Navigation("Markets");
                });
#pragma warning restore 612, 618
        }
    }
}
